(function(){"use strict";
function $(s,r){return (r||document).querySelector(s)}
function setErro(m){const b=$("#erroGlobal"); if(!b)return; b.textContent=m||""; b.classList.toggle("show",!!m)}
function setInfo(m){const b=$("#infoGlobal"); if(!b)return; b.textContent=m||""; b.classList.toggle("show",!!m)}
function setTitulo(t,st){const a=$("#tituloTela"),b=$("#subtituloTela"); if(a)a.textContent=t||""; if(b)b.textContent=st||""}
function rotaAtual(){const r=(location.hash||"#dashboard").replace("#","").trim(); const v=["dashboard","clientes","chamados","orcamentos","ordens","compras","despesas","financeiro","agenda","recorrencia","configuracoes"]; return v.includes(r)?r:"dashboard"}
function montarShell(){const app=document.getElementById("app"); if(!app)return; app.innerHTML=`<div class="layout"><aside class="sidebar"><div class="brand-box"><div class="brand-title">SGB</div><div class="brand-sub">Serralheria</div></div><nav class="nav"><a href="#dashboard" data-route="dashboard">Dashboard</a><a href="#clientes" data-route="clientes">Clientes</a><a href="#chamados" data-route="chamados">Chamados</a><a href="#orcamentos" data-route="orcamentos">Orçamentos</a><a href="#ordens" data-route="ordens">Ordens de Serviço</a><a href="#compras" data-route="compras">Compras</a><a href="#despesas" data-route="despesas">Contas a Pagar</a><a href="#financeiro" data-route="financeiro">Financeiro</a><a href="#agenda" data-route="agenda">Agenda</a><a href="#recorrencia" data-route="recorrencia">Recorrência</a><a href="#configuracoes" data-route="configuracoes">Configurações</a></nav></aside><main class="main"><div class="topbar"><div><div class="page-title" id="tituloTela">Dashboard</div><div class="hero-sub" id="subtituloTela">Visão geral do sistema</div></div><div class="badge-status" id="badgeConexao">Conectando...</div></div><div class="content"><div class="alert error" id="erroGlobal"></div><div class="alert info" id="infoGlobal"></div><div id="conteudoTela"></div></div></main></div>`; document.querySelectorAll(".nav a").forEach(a=>a.addEventListener("click",e=>{e.preventDefault(); location.hash=a.getAttribute("data-route")}))}
function atualizarBadgeConexao(){const b=$("#badgeConexao"); if(b) b.textContent=window.sb&&window.sb.db?"Conectado":"Sem conexão"}
function marcarMenuAtivo(){const r=rotaAtual(); document.querySelectorAll(".nav a").forEach(a=>a.classList.toggle("active",a.getAttribute("data-route")===r))}
function placeholder(t,d){setTitulo(t,d); $("#conteudoTela").innerHTML=`<div class="panel"><h2>${t}</h2><div class="panel-sub">${d}</div><div class="placeholder-big">Módulo em preparação.</div></div>`}
async function renderizarDashboard(){setTitulo("Dashboard","Visão geral do sistema"); if(window.ModuloDashboard&&typeof window.ModuloDashboard.renderizarDashboard==="function"){return window.ModuloDashboard.renderizarDashboard({areaId:"conteudoTela",sb:window.sb,setErro,setInfo,setTitulo})} return placeholder("Dashboard","Módulo não carregado.")}
async function renderizarTelaAtual(){setErro(""); setInfo(""); atualizarBadgeConexao(); marcarMenuAtivo(); const r=rotaAtual();
if(r==="dashboard") return renderizarDashboard();
if(r==="chamados"){setTitulo("Chamados","Controle de tickets e atendimento"); if(window.ModuloChamados&&typeof window.ModuloChamados.listarChamados==="function"&&window.sb&&window.sb.db&&window.sb.companyId){return window.ModuloChamados.listarChamados({areaId:"conteudoTela",sb:window.sb,companyId:window.sb.companyId,portalToken:window.sb.portalToken||""})} return placeholder("Chamados","Módulo de chamados não carregado.")}
if(r==="orcamentos"){setTitulo("Orçamentos","Lista, edição de itens e aprovação"); if(window.ModuloOrcamentos&&typeof window.ModuloOrcamentos.listarOrcamentos==="function"&&window.sb&&window.sb.db&&window.sb.companyId){return window.ModuloOrcamentos.listarOrcamentos({areaId:"conteudoTela",sb:window.sb,companyId:window.sb.companyId})} return placeholder("Orçamentos","Módulo de orçamentos não carregado.")}
if(r==="ordens"){setTitulo("Ordens de Serviço","Produção, instalação e checklist operacional"); if(window.ModuloOrdens&&typeof window.ModuloOrdens.listarOrdens==="function"&&window.sb&&window.sb.db&&window.sb.companyId){return window.ModuloOrdens.listarOrdens({areaId:"conteudoTela",sb:window.sb,companyId:window.sb.companyId})} return placeholder("Ordens de Serviço","Módulo de ordens não carregado.")}
if(r==="compras"){setTitulo("Compras","Compras vinculadas à Ordem de Serviço e custo real"); if(window.ModuloCompras&&typeof window.ModuloCompras.listarCompras==="function"&&window.sb&&window.sb.db&&window.sb.companyId){return window.ModuloCompras.listarCompras({areaId:"conteudoTela",sb:window.sb,companyId:window.sb.companyId,workorderId:window.__osSelecionadaId||null})} return placeholder("Compras","Módulo de compras não carregado.")}
if(r==="despesas"){setTitulo("Contas a Pagar","Despesas administrativas e integração com fluxo de caixa"); if(window.ModuloDespesas&&typeof window.ModuloDespesas.listarDespesas==="function"&&window.sb&&window.sb.db&&window.sb.companyId){return window.ModuloDespesas.listarDespesas({areaId:"conteudoTela",sb:window.sb,companyId:window.sb.companyId})} return placeholder("Contas a Pagar","Módulo de despesas não carregado.")}
if(r==="financeiro"){setTitulo("Financeiro","Executivo, contas a receber, fluxo de caixa, DRE e previsão"); if(window.ModuloFinanceiro&&typeof window.ModuloFinanceiro.listarFinanceiro==="function"&&window.sb&&window.sb.db&&window.sb.companyId){return window.ModuloFinanceiro.listarFinanceiro({areaId:"conteudoTela",sb:window.sb,companyId:window.sb.companyId})} return placeholder("Financeiro","Módulo financeiro não carregado.")}
if(r==="agenda"){setTitulo("Agenda","Agenda operacional da equipe"); if(window.ModuloAgenda&&typeof window.ModuloAgenda.renderizarAgenda==="function"){return window.ModuloAgenda.renderizarAgenda({areaId:"conteudoTela",sb:window.sb,setErro,setInfo,setTitulo})} return placeholder("Agenda","Módulo de agenda não carregado.")}
if(r==="recorrencia"){setTitulo("Recorrência","Clientes avulsos, contratos e SLA"); if(window.ModuloRecorrencia&&typeof window.ModuloRecorrencia.renderizarRecorrencia==="function"){return window.ModuloRecorrencia.renderizarRecorrencia({areaId:"conteudoTela",sb:window.sb,setErro,setInfo,setTitulo})} return placeholder("Recorrência","Módulo de recorrência não carregado.")}
if(r==="clientes") return placeholder("Clientes","Cadastro e consulta de clientes.");
if(r==="configuracoes") return placeholder("Configurações","Ajustes do sistema.")}
document.addEventListener("DOMContentLoaded",function(){montarShell(); renderizarTelaAtual(); window.addEventListener("hashchange",renderizarTelaAtual); setTimeout(renderizarTelaAtual,500)});})();