(function () {
  "use strict";

  function fmtInt(v){return new Intl.NumberFormat("pt-BR").format(Number(v||0));}
  function fmtMoney(v){return new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"}).format(Number(v||0));}
  function norm(v){return String(v||"").trim().toLowerCase();}
  function todayISO(){const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`;}
  function plusDays(iso,days){const d=new Date(iso+"T00:00:00");d.setDate(d.getDate()+days);return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`;}
  function dateBR(raw){if(!raw)return "—";const d=new Date(String(raw).length<=10?raw+"T00:00:00":raw);return Number.isNaN(d.getTime())?String(raw):d.toLocaleDateString("pt-BR");}
  function panel(title,subtitle,body){return `<div class="panel"><h2>${title}</h2>${subtitle?`<div class="panel-sub">${subtitle}</div>`:""}${body}</div>`;}
  function row(a,b,c,d){return `<div class="line-item"><div class="line-top"><div>${a||"—"}</div><div>${b||""}</div></div><div>${c||"—"}</div>${d?`<div class="muted" style="margin-top:6px;">${d}</div>`:""}</div>`;}
  function badge(status){const s=norm(status);let cls="status-pill";if(["ativo","finalizado","quitado","pago"].includes(s))cls+=" status-finalizado";else if(["suspenso","em_analise","aguardando_analise"].includes(s))cls+=" status-aguardando_analise";else if(["cancelado"].includes(s))cls+=" status-cancelado";else cls+=" status-aberto";return `<span class="${cls}">${status||"—"}</span>`;}
  async function safeSelect(db,table,columns,companyId,extraBuilder){try{let q=db.from(table).select(columns).eq("company_id",companyId);if(typeof extraBuilder==="function")q=extraBuilder(q);const r=await q;if(r.error)throw r.error;return {ok:true,data:r.data||[]};}catch(e){return {ok:false,error:e};}}
  function monthsBack(count){const out=[];const now=new Date();for(let i=count-1;i>=0;i--){const d=new Date(now.getFullYear(),now.getMonth()-i,1);const key=`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}`;const label=d.toLocaleDateString("pt-BR",{month:"short",year:"2-digit"});out.push({key,label});}return out;}
  function aggregateCountByMonth(items,field,months){const map={};months.forEach(m=>map[m.key]=0);(items||[]).forEach(item=>{const raw=item[field];if(!raw)return;const d=new Date(String(raw).length<=10?raw+"T00:00:00":raw);if(Number.isNaN(d.getTime()))return;const key=`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}`;if(key in map)map[key]+=1;});return months.map(m=>map[m.key]||0);}
  function aggregateMoneyByMonth(items,fieldDate,fieldAmount,months){const map={};months.forEach(m=>map[m.key]=0);(items||[]).forEach(item=>{const raw=item[fieldDate];if(!raw)return;const d=new Date(String(raw).length<=10?raw+"T00:00:00":raw);if(Number.isNaN(d.getTime()))return;const key=`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}`;if(key in map)map[key]+=Number(item[fieldAmount]||0);});return months.map(m=>map[m.key]||0);}
  function drawCharts(months,metrics){if(typeof window.Chart==="undefined")return;const common={responsive:true,maintainAspectRatio:false,plugins:{legend:{labels:{color:"#edf4ff"}}},scales:{x:{ticks:{color:"#c8d8f4"},grid:{color:"rgba(36,59,97,.35)"}},y:{ticks:{color:"#c8d8f4"},grid:{color:"rgba(36,59,97,.35)"}}}};const a=document.getElementById("grafTicketsMes");if(a)new window.Chart(a,{type:"line",data:{labels:months.map(m=>m.label),datasets:[{label:"Chamados",data:metrics.ticketsByMonth,borderColor:"#3d86ff",backgroundColor:"rgba(61,134,255,.18)",fill:true,tension:.3}]},options:common});const b=document.getElementById("grafMRRMes");if(b)new window.Chart(b,{type:"bar",data:{labels:months.map(m=>m.label),datasets:[{label:"Receita recorrente",data:metrics.contractRevenueByMonth,backgroundColor:"rgba(20,195,142,.78)",borderColor:"#14c38e",borderWidth:1}]},options:common});const c=document.getElementById("grafRecebiveis");if(c)new window.Chart(c,{type:"doughnut",data:{labels:["Em aberto","Pagos"],datasets:[{data:[metrics.openReceivables,metrics.paidReceivables],backgroundColor:["#f6b73c","#14c38e"],borderColor:"#07111f",borderWidth:2}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{position:"bottom",labels:{color:"#edf4ff"}}}}});}
  function renderContracts(contracts){if(!contracts.length)return `<div class="empty">Nenhum contrato ativo encontrado.</div>`;return `<div class="list-lines">${contracts.slice(0,8).map(c=>row(c.name||"Contrato",badge(c.status),`${c.customer_name||"Cliente"} • ${fmtMoney(c.amount||0)}`,[c.next_billing_date?`Próxima cobrança: ${dateBR(c.next_billing_date)}`:"",c.sla_name||""].filter(Boolean).join(" • "))).join("")}</div>`;}
  function renderReceivables(items){if(!items.length)return `<div class="empty">Nenhuma cobrança encontrada.</div>`;return `<div class="list-lines">${items.slice(0,8).map(r=>row(dateBR(r.due_date),badge(r.paid?"pago":"aberto"),`${r.customer_name||"Cliente"} • ${fmtMoney(r.amount||0)}`,r.contract_name?`Contrato: ${r.contract_name}`:"")).join("")}</div>`;}
  function renderTickets(items){if(!items.length)return `<div class="empty">Nenhum chamado recente.</div>`;return `<div class="list-lines">${items.slice(0,8).map(t=>row(dateBR(t.created_at),badge(t.status),`${t.client_name||"Sem nome"}${t.client_phone?" — "+t.client_phone:""}`,t.description||"")).join("")}</div>`;}
  function renderCommercialIntel(intel){return `<div class="list-lines">${row("Conversão",fmtInt(intel.convertedCustomers),"Clientes que viraram recorrentes",intel.convertedNames||"Sem conversões detectadas")}${row("Sumiço",fmtInt(intel.sleepingCustomers),"Clientes sem atividade há 60+ dias",intel.sleepingNames||"Nenhum cliente inativo detectado")}${row("Ticket médio",intel.avgTicketsPerClientLabel,"Média de chamados por cliente",`${fmtInt(intel.totalClientsWithTickets)} cliente(s) com histórico`) }${row("Mais lucrativo",fmtMoney(intel.topClientRevenue),intel.topClientName||"Nenhum cliente líder ainda",intel.topClientNote||"Sem base suficiente")}</div>`;}
  async function renderizarDashboard(opts){
    const areaId=opts&&opts.areaId?opts.areaId:"conteudoTela", sb=opts&&opts.sb?opts.sb:window.sb, setErro=opts&&opts.setErro?opts.setErro:function(){}, setInfo=opts&&opts.setInfo?opts.setInfo:function(){}, setTitulo=opts&&opts.setTitulo?opts.setTitulo:function(){};
    setTitulo("Dashboard","Painel executivo SaaS do sistema"); setErro(""); setInfo("");
    const alvo=document.getElementById(areaId); if(!alvo)return;
    alvo.innerHTML=panel("Dashboard","Carregando indicadores executivos...",`<div class="placeholder-big">Aguarde, consolidando operação, contratos e inteligência comercial.</div>`);
    if(!(sb&&sb.db&&sb.companyId)){setInfo("Conexão carregada, mas companyId ainda não está disponível."); return;}
    try{
      const hoje=todayISO(), limite7=plusDays(hoje,7), corteDormencia=plusDays(hoje,-60);
      const [ticketsResp,customersResp,contractsResp,slaResp,receivablesResp]=await Promise.all([
        safeSelect(sb.db,"tickets","id, created_at, client_name, client_phone, description, status, customer_id",sb.companyId),
        safeSelect(sb.db,"customers","id, name, phone, created_at",sb.companyId),
        safeSelect(sb.db,"contracts","id, customer_id, sla_plan_id, start_date, next_billing_date, status, name, amount, created_at",sb.companyId),
        safeSelect(sb.db,"sla_plans","id, name, hours_to_expire, created_at",sb.companyId),
        safeSelect(sb.db,"receivables","id, contract_id, due_date, amount, paid, paid_at, customer_id, created_at",sb.companyId)
      ]);
      const tickets=ticketsResp.ok?ticketsResp.data:[], customers=customersResp.ok?customersResp.data:[], contracts=contractsResp.ok?contractsResp.data:[], slaPlans=slaResp.ok?slaResp.data:[], receivables=receivablesResp.ok?receivablesResp.data:[];
      const customerMap={}, slaMap={}, contractMap={}; customers.forEach(c=>customerMap[c.id]=c); slaPlans.forEach(s=>slaMap[s.id]=s); contracts.forEach(c=>contractMap[c.id]=c);
      const activeContracts=contracts.filter(c=>norm(c.status)==="ativo"), suspendedContracts=contracts.filter(c=>norm(c.status)==="suspenso"), canceledContracts=contracts.filter(c=>norm(c.status)==="cancelado");
      const mrr=activeContracts.reduce((a,c)=>a+Number(c.amount||0),0), arr=mrr*12;
      const paidReceivables=receivables.filter(r=>!!r.paid).length, openReceivables=receivables.filter(r=>!r.paid).length, overdueReceivables=receivables.filter(r=>!r.paid&&r.due_date&&String(r.due_date)<hoje).length, dueSoonReceivables=receivables.filter(r=>!r.paid&&r.due_date&&String(r.due_date)>=hoje&&String(r.due_date)<=limite7).length;
      const openTickets=tickets.filter(t=>["aberto","open"].includes(norm(t.status))).length, analysisTickets=tickets.filter(t=>["em_analise","aguardando_analise"].includes(norm(t.status))).length, progressTickets=tickets.filter(t=>norm(t.status)==="em_andamento").length;
      const recurringCustomersSet=new Set(activeContracts.map(c=>c.customer_id).filter(Boolean)), recurringCustomers=recurringCustomersSet.size;
      const avulsoKeys=new Set(); tickets.forEach(t=>{if(t.customer_id&&recurringCustomersSet.has(t.customer_id))return; const key=`${String(t.client_name||"").trim().toLowerCase()}||${String(t.client_phone||"").trim()}`; if(key!=="||") avulsoKeys.add(key);}); const avulsoClients=avulsoKeys.size;
      const months=monthsBack(6), ticketsByMonth=aggregateCountByMonth(tickets,"created_at",months), contractRevenueByMonth=aggregateMoneyByMonth(activeContracts,"start_date","amount",months);
      const ticketsPorCliente={}; tickets.forEach(t=>{const key=t.customer_id||`${String(t.client_name||"").trim().toLowerCase()}||${String(t.client_phone||"").trim()}`; if(!key)return; if(!ticketsPorCliente[key]) ticketsPorCliente[key]={count:0,lastDate:"",name:t.client_name||"",customerId:t.customer_id||null}; ticketsPorCliente[key].count+=1; if(t.created_at&&String(t.created_at)>String(ticketsPorCliente[key].lastDate||"")) ticketsPorCliente[key].lastDate=t.created_at; if(!ticketsPorCliente[key].name&&t.client_name) ticketsPorCliente[key].name=t.client_name;});
      const totalClientsWithTickets=Object.keys(ticketsPorCliente).length, avgTicketsPerClient=totalClientsWithTickets?(tickets.length/totalClientsWithTickets):0, avgTicketsPerClientLabel=avgTicketsPerClient.toFixed(1).replace(".",",");
      const convertedCustomersList=activeContracts.filter(c=>c.customer_id&&tickets.some(t=>t.customer_id===c.customer_id)).map(c=>customerMap[c.customer_id]?.name||c.name||"Cliente");
      const convertedCustomers=convertedCustomersList.length, convertedNames=convertedCustomersList.slice(0,3).join(" • ");
      const sleepingList=Object.values(ticketsPorCliente).filter(x=>x.lastDate&&String(x.lastDate).slice(0,10)<corteDormencia).filter(x=>!(x.customerId&&recurringCustomersSet.has(x.customerId))).sort((a,b)=>String(a.lastDate||"").localeCompare(String(b.lastDate||"")));
      const sleepingCustomers=sleepingList.length, sleepingNames=sleepingList.slice(0,3).map(x=>x.name||"Cliente").join(" • ");
      const revenueByCustomer={}; receivables.filter(r=>!!r.paid).forEach(r=>{const key=r.customer_id||"sem_cliente"; if(!revenueByCustomer[key]) revenueByCustomer[key]=0; revenueByCustomer[key]+=Number(r.amount||0);}); if(!Object.keys(revenueByCustomer).length){activeContracts.forEach(c=>{const key=c.customer_id||"sem_cliente"; if(!revenueByCustomer[key]) revenueByCustomer[key]=0; revenueByCustomer[key]+=Number(c.amount||0);});}
      let topClientId=null, topClientRevenue=0; Object.entries(revenueByCustomer).forEach(([k,v])=>{if(Number(v||0)>topClientRevenue){topClientRevenue=Number(v||0); topClientId=k;}});
      const topClientName=topClientId&&customerMap[topClientId]?customerMap[topClientId].name:"", topClientNote=topClientRevenue?"Maior receita recorrente / recebida registrada":"";
      const contractsView=activeContracts.map(c=>({...c,customer_name:customerMap[c.customer_id]?customerMap[c.customer_id].name:"",sla_name:slaMap[c.sla_plan_id]?`${slaMap[c.sla_plan_id].name} • ${slaMap[c.sla_plan_id].hours_to_expire||0}h`:""})).sort((a,b)=>String(a.next_billing_date||"").localeCompare(String(b.next_billing_date||"")));
      const receivablesView=receivables.map(r=>({...r,contract_name:contractMap[r.contract_id]?contractMap[r.contract_id].name:"",customer_name:customerMap[r.customer_id]?customerMap[r.customer_id].name:""})).sort((a,b)=>String(b.due_date||"").localeCompare(String(a.due_date||"")));
      const latestTickets=[...tickets].sort((a,b)=>String(b.created_at||"").localeCompare(String(a.created_at||"")));
      alvo.innerHTML=`<div class="cards" style="grid-template-columns:repeat(7,minmax(0,1fr));"><div class="card"><div class="card-label">MRR</div><div class="card-value">${fmtMoney(mrr)}</div></div><div class="card"><div class="card-label">ARR</div><div class="card-value">${fmtMoney(arr)}</div></div><div class="card"><div class="card-label">Contratos Ativos</div><div class="card-value">${fmtInt(activeContracts.length)}</div></div><div class="card"><div class="card-label">Cobranças em Aberto</div><div class="card-value">${fmtInt(openReceivables)}</div></div><div class="card"><div class="card-label">Chamados Abertos</div><div class="card-value">${fmtInt(openTickets)}</div></div><div class="card"><div class="card-label">Clientes Recorrentes</div><div class="card-value">${fmtInt(recurringCustomers)}</div></div><div class="card"><div class="card-label">Clientes Avulsos</div><div class="card-value">${fmtInt(avulsoClients)}</div></div></div>
      <div class="grid-2" style="margin-top:16px;">${panel("Chamados por Mês","Evolução da operação",`<div style="height:320px;"><canvas id="grafTicketsMes"></canvas></div>`)}${panel("Receita Recorrente","Base mensal de contratos ativos",`<div style="height:320px;"><canvas id="grafMRRMes"></canvas></div>`)}</div>
      <div class="grid-2" style="margin-top:16px;">${panel("Cobranças","Situação aberta x paga",`<div style="height:320px;"><canvas id="grafRecebiveis"></canvas></div>`)}${panel("Resumo Executivo","Indicadores principais do negócio",`<div class="list-lines">${row("MRR",fmtMoney(mrr),"Receita mensal recorrente",`Contratos ativos: ${fmtInt(activeContracts.length)}`)}${row("ARR",fmtMoney(arr),"Receita anual recorrente","MRR x 12")}${row("Cobranças",fmtInt(openReceivables),"Cobranças em aberto",`Vencidas: ${fmtInt(overdueReceivables)} • 7 dias: ${fmtInt(dueSoonReceivables)}`)}${row("SLA",fmtInt(openTickets),"Chamados abertos",`Em análise: ${fmtInt(analysisTickets)} • Em andamento: ${fmtInt(progressTickets)}`)}</div>`)}</div>
      <div class="grid-2" style="margin-top:16px;">${panel("Contratos Ativos","Clientes recorrentes e próxima cobrança",renderContracts(contractsView))}${panel("Cobranças Recentes","Recebíveis vinculados a contratos",renderReceivables(receivablesView))}</div>
      <div class="grid-2" style="margin-top:16px;">${panel("Últimos Chamados","Fila operacional recente",renderTickets(latestTickets))}${panel("Inteligência Comercial","Leituras para vendas e retenção",renderCommercialIntel({convertedCustomers,convertedNames,sleepingCustomers,sleepingNames,avgTicketsPerClientLabel,totalClientsWithTickets,topClientRevenue,topClientName,topClientNote}))}</div>
      <div class="grid-2" style="margin-top:16px;">${panel("Alertas","Pontos de atenção do sistema",`<div class="list-lines">${row("Contratos",badge("ativo"),"Ativos / Suspensos / Cancelados",`${fmtInt(activeContracts.length)} / ${fmtInt(suspendedContracts.length)} / ${fmtInt(canceledContracts.length)}`)}${row("Recebíveis",badge("aberto"),"Cobranças vencidas",`${fmtInt(overdueReceivables)} vencida(s) • ${fmtInt(dueSoonReceivables)} vence(m) em 7 dias`)}${row("Tickets",badge("aberto"),"Abertos / Em análise / Em andamento",`${fmtInt(openTickets)} / ${fmtInt(analysisTickets)} / ${fmtInt(progressTickets)}`)}${row("Base comercial",badge("ativo"),"Recorrentes / Avulsos",`${fmtInt(recurringCustomers)} / ${fmtInt(avulsoClients)}`)}</div>`)}${panel("Leitura Comercial","Indicadores derivados da base atual",`<div class="list-lines">${row("Conversão",fmtInt(convertedCustomers),"Clientes que viraram recorrentes",convertedNames||"Sem nomes para exibir")}${row("Inatividade",fmtInt(sleepingCustomers),"Clientes sem atividade há 60+ dias",sleepingNames||"Nenhum detectado")}${row("Média",avgTicketsPerClientLabel,"Chamados por cliente",`${fmtInt(totalClientsWithTickets)} cliente(s) com tickets`)}${row("Top cliente",fmtMoney(topClientRevenue),topClientName||"Sem destaque",topClientNote||"")}</div>`)}</div>`;
      drawCharts(months,{ticketsByMonth,contractRevenueByMonth,openReceivables,paidReceivables});
    }catch(erro){
      setErro("Falha ao carregar dashboard: "+(erro.message||erro));
      alvo.innerHTML=panel("Dashboard","Não foi possível montar o painel executivo.",`<div class="placeholder-big">Verifique acesso às tabelas tickets, customers, contracts, sla_plans e receivables.</div>`);
    }
  }

  window.ModuloDashboard={renderizarDashboard:renderizarDashboard};
})();