(function(){"use strict";
function $(s,r){return (r||document).querySelector(s)} function $all(s,r){return Array.from((r||document).querySelectorAll(s))}
function inteiro(v){return new Intl.NumberFormat("pt-BR").format(Number(v||0))}
function moeda(v){return new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"}).format(Number(v||0))}
function fmtData(d){if(!d)return "—"; const x=new Date(String(d).length<=10?d+"T00:00:00":d); return x.toLocaleDateString("pt-BR")}
function hojeISO(){const d=new Date(); return [d.getFullYear(),String(d.getMonth()+1).padStart(2,"0"),String(d.getDate()).padStart(2,"0")].join("-")}
function normalizar(s){return String(s||"").trim().toLowerCase()}
function panel(t,s,b){return `<div class="panel"><h2>${t}</h2>${s?`<div class="panel-sub">${s}</div>`:""}${b}</div>`}
function pill(st){const s=normalizar(st); let cls="status-pill"; if(s==="ativo"||s==="renovado")cls+=" status-finalizado"; else if(s==="suspenso")cls+=" status-aguardando_analise"; else if(s==="cancelado"||s==="encerrado")cls+=" status-cancelado"; else cls+=" status-aberto"; return `<span class="${cls}">${st||"—"}</span>`}
function linha(a,b,c,d,e){return `<div class="line-item"><div class="line-top"><div>${a||"—"}</div><div>${b||""}</div></div><div>${c||"—"}</div>${d?`<div class="muted" style="margin-top:6px;">${d}</div>`:""}${e?`<div style="margin-top:10px;display:flex;gap:8px;flex-wrap:wrap;">${e}</div>`:""}</div>`}
async function safeSelect(db,table,cols,cid){try{const r=await db.from(table).select(cols).eq("company_id",cid); if(r.error) throw r.error; return {ok:true,data:r.data||[]}}catch(e){return {ok:false,error:e}}}
async function safeInsert(db,table,payload){const r=await db.from(table).insert(payload).select().limit(1); if(r.error) throw r.error; return (r.data||[])[0]||null}
async function safeUpdate(db,table,payload,filters){let q=db.from(table).update(payload); (filters||[]).forEach(([f,v])=>q=q.eq(f,v)); const r=await q.select().limit(1); if(r.error) throw r.error; return (r.data||[])[0]||null}
function guessAmount(p){return Number((p&& (p.amount||p.monthly_amount||p.valor||p.price))||0)}
function slaDescricao(p){if(!p) return "—"; const n=p.name||p.nome||"Plano"; const h=p.sla_hours||p.hours||p.response_hours||p.deadline_hours||null; return h?`${n} • ${h}h`:n}
function avulsosFromTickets(tickets,customers){const mapC={}; (customers||[]).forEach(c=>mapC[`${String(c.name||"").trim().toLowerCase()}||${String(c.phone||"").trim()}`]=c); const m={}; (tickets||[]).forEach(t=>{const nome=String(t.client_name||"").trim(), fone=String(t.client_phone||"").trim(); if(!nome&&!fone)return; const k=`${nome.toLowerCase()}||${fone}`, c=mapC[k]||null; if(!m[k]) m[k]={client_name:nome||"Sem nome",client_phone:fone||"",total_chamados:0,ultimo_status:t.status||"",ultima_data:t.created_at||null,customer_id:c?c.id:null}; m[k].total_chamados+=1; if(t.created_at&&(!m[k].ultima_data||String(t.created_at)>String(m[k].ultima_data))){m[k].ultima_data=t.created_at; m[k].ultimo_status=t.status||""}}); return Object.values(m).sort((a,b)=>String(b.ultima_data||"").localeCompare(String(a.ultima_data||"")))}
function formHtml(customers,slaPlans){const copt=(customers||[]).map(c=>`<option value="${c.id}">${c.name}${c.phone?" — "+c.phone:""}</option>`).join(""); const sopt=(slaPlans||[]).map(p=>`<option value="${p.id}" data-default-amount="${guessAmount(p)}">${slaDescricao(p)}</option>`).join(""); return `<form id="formRecorrencia" class="form-grid-2"><input type="hidden" id="rcContratoId" value="" /><div class="field"><label>Cliente</label><select id="rcCustomerId" required><option value="">Selecione</option>${copt}</select></div><div class="field"><label>Nome do Contrato</label><input id="rcName" type="text" placeholder="Ex.: Plano mensal manutenção portões" /></div><div class="field"><label>Plano SLA</label><select id="rcSlaPlanId" required><option value="">Selecione</option>${sopt}</select></div><div class="field"><label>Valor Mensal</label><input id="rcAmount" type="number" step="0.01" min="0" placeholder="0,00" /></div><div class="field"><label>Início do Contrato</label><input id="rcStartDate" type="date" /></div><div class="field"><label>Próxima Cobrança</label><input id="rcNextBillingDate" type="date" /></div><div class="field"><label>Status</label><select id="rcStatus"><option value="ativo">Ativo</option><option value="suspenso">Suspenso</option><option value="cancelado">Cancelado</option></select></div><div class="field"><label>Resumo</label><div class="muted">O operador define a próxima cobrança. O sistema não armazena dados de cartão.</div></div><div style="grid-column:1/-1;display:flex;gap:10px;flex-wrap:wrap;margin-top:8px;"><button type="submit" class="btn-primary">Salvar contrato</button><button type="button" id="btnNovoContrato" class="btn-secondary">Novo contrato</button><button type="button" id="btnProcessarRecorrencia" class="btn-secondary">Processar recorrências agora</button></div></form>`}
function renderContratos(contratos){if(!contratos.length)return `<div class="empty">Nenhum contrato cadastrado ainda.</div>`; return `<div class="list-lines">${contratos.map(c=>linha(c.name||c.customer_name||"Contrato",pill(c.status),`${c.client_name||c.customer_name||"Cliente"} • ${moeda(c.amount||0)}`,[c.start_date?`Início: ${fmtData(c.start_date)}`:"",c.next_billing_date?`Próxima cobrança: ${fmtData(c.next_billing_date)}`:"",c.sla_name?`SLA: ${c.sla_name}`:""].filter(Boolean).join(" • "),`<button class="btn-secondary" data-action="editar-contrato" data-id="${c.id}">Editar</button><button class="btn-secondary" data-action="cancelar-contrato" data-id="${c.id}">Cancelar</button><button class="btn-secondary" data-action="renovar-contrato" data-id="${c.id}">Renovar</button>`)).join("")}</div>`}
function renderAvulsos(av){if(!av.length)return `<div class="empty">Nenhum cliente avulso encontrado a partir dos chamados.</div>`; return `<div class="list-lines">${av.slice(0,14).map((c,idx)=>linha(c.ultima_data?fmtData(c.ultima_data):"—",`<span class="status-pill status-aberto">Avulso</span>`,`${c.client_name}${c.client_phone?" — "+c.client_phone:""}`,`${inteiro(c.total_chamados)} chamado(s) • último status: ${c.ultimo_status||"—"}`,`<button class="btn-secondary" data-action="converter-avulso" data-idx="${idx}">Converter em recorrente</button>${c.customer_id?`<button class="btn-secondary" data-action="usar-cadastro" data-customer-id="${c.customer_id}">Usar cadastro existente</button>`:""}`)).join("")}</div>`}
function contratosMerged(contratos,slaPlans,customers){const sp={}, cu={}; (slaPlans||[]).forEach(p=>sp[p.id]=p); (customers||[]).forEach(c=>cu[c.id]=c); return (contratos||[]).map(c=>({...c,sla_name:sp[c.sla_plan_id]?slaDescricao(sp[c.sla_plan_id]):"",customer_name:c.customer_name||c.client_name||(cu[c.customer_id]?cu[c.customer_id].name:"")}))}
async function renderizarRecorrencia(opts){const areaId=opts&&opts.areaId?opts.areaId:"conteudoTela", sb=opts&&opts.sb?opts.sb:window.sb, setErro=opts&&opts.setErro?opts.setErro:function(){}, setInfo=opts&&opts.setInfo?opts.setInfo:function(){}, setTitulo=opts&&opts.setTitulo?opts.setTitulo:function(){}; setTitulo("Recorrência","Clientes avulsos, contratos e SLA"); setErro(""); setInfo(""); const alvo=document.getElementById(areaId); if(!alvo)return; alvo.innerHTML=panel("Recorrência","Carregando contratos, clientes avulsos, SLA e financeiro recorrente...",`<div class="placeholder-big">Aguarde, montando o módulo de recorrência.</div>`); if(!(sb&&sb.db&&sb.companyId)){setInfo("Conexão carregada, mas companyId ainda não está disponível."); return}
try{
 const [ticketsResp,contratosResp,customersResp,slaResp,receivablesResp]=await Promise.all([safeSelect(sb.db,"tickets","id, client_name, client_phone, status, created_at",sb.companyId),safeSelect(sb.db,"contracts","id, company_id, customer_id, sla_plan_id, start_date, next_billing_date, status, created_at, name, amount",sb.companyId),safeSelect(sb.db,"customers","id, name, phone, created_at",sb.companyId),safeSelect(sb.db,"sla_plans","*",sb.companyId),safeSelect(sb.db,"receivables","id, contract_id, due_date, amount, paid, created_at",sb.companyId)]);
 const tickets=ticketsResp.ok?ticketsResp.data:[], customers=customersResp.ok?customersResp.data:[], slaPlans=slaResp.ok?slaResp.data:[], receivables=receivablesResp.ok?receivablesResp.data:[], contratos=contratosMerged(contratosResp.ok?contratosResp.data:[],slaPlans,customers), avulsos=avulsosFromTickets(tickets,customers), ativos=contratos.filter(c=>normalizar(c.status)==="ativo"), suspensos=contratos.filter(c=>normalizar(c.status)==="suspenso"), receita=ativos.reduce((a,i)=>a+Number(i.amount||0),0), abertas=receivables.filter(r=>!r.paid&&!!r.contract_id).length;
 const avisos=[]; if(!ticketsResp.ok) avisos.push("Não foi possível ler tickets."); if(!customersResp.ok) avisos.push("Não foi possível ler customers."); if(!contratosResp.ok) avisos.push("Não foi possível ler contracts."); if(!slaResp.ok) avisos.push("Não foi possível ler sla_plans."); if(!receivablesResp.ok) avisos.push("Não foi possível ler receivables."); if(avisos.length) setInfo(avisos.join(" "));
 alvo.innerHTML=`<div class="cards" style="grid-template-columns:repeat(5,minmax(0,1fr));"><div class="card"><div class="card-label">Clientes Avulsos</div><div class="card-value">${inteiro(avulsos.length)}</div></div><div class="card"><div class="card-label">Contratos Ativos</div><div class="card-value">${inteiro(ativos.length)}</div></div><div class="card"><div class="card-label">Contratos Suspensos</div><div class="card-value">${inteiro(suspensos.length)}</div></div><div class="card"><div class="card-label">Receita Mensal Contratada</div><div class="card-value">${moeda(receita)}</div></div><div class="card"><div class="card-label">Cobranças em Aberto</div><div class="card-value">${inteiro(abertas)}</div></div></div><div class="grid-2" style="margin-top:16px;">${panel("Criar / Editar Contrato","O operador define cliente, SLA, valor e a próxima cobrança",formHtml(customers,slaPlans))}${panel("Clientes Avulsos","Clientes que entram direto via chamados e podem virar recorrentes",renderAvulsos(avulsos))}</div><div class="grid-2" style="margin-top:16px;">${panel("Contratos Cadastrados","Situação atual dos vínculos recorrentes",renderContratos(contratos))}${panel("Regras Operacionais","Lógica definida para a recorrência",`<div class="list-lines">${linha("Avulso","","Cliente que entra pelo chamado","Sem contrato • cobrança individual")}${linha("Recorrente","","Cliente com contrato ativo","Mensalidade + SLA aplicado nos chamados")}${linha("Cobrança","","Data escolhida pelo operador","O sistema gera receivable recorrente sem guardar cartão")}${linha("Segurança","","Sem dados de cartão","Pode registrar método preferido, mas nunca dados sensíveis")}</div>`)}</div>`;
 const state={customers,contratos,avulsos,slaPlans,sb}; const form=$("#formRecorrencia",alvo), contractId=$("#rcContratoId",alvo), customerId=$("#rcCustomerId",alvo), name=$("#rcName",alvo), slaPlanId=$("#rcSlaPlanId",alvo), amount=$("#rcAmount",alvo), startDate=$("#rcStartDate",alvo), nextBillingDate=$("#rcNextBillingDate",alvo), status=$("#rcStatus",alvo), btnNovo=$("#btnNovoContrato",alvo), btnProc=$("#btnProcessarRecorrencia",alvo);
 startDate.value=hojeISO(); nextBillingDate.value=hojeISO();
 function resetForm(){contractId.value=""; customerId.value=""; name.value=""; slaPlanId.value=""; amount.value=""; startDate.value=hojeISO(); nextBillingDate.value=hojeISO(); status.value="ativo"}
 function preencher(c){contractId.value=c.id||""; customerId.value=c.customer_id||""; name.value=c.name||""; slaPlanId.value=c.sla_plan_id||""; amount.value=Number(c.amount||0); startDate.value=c.start_date?String(c.start_date).slice(0,10):hojeISO(); nextBillingDate.value=c.next_billing_date?String(c.next_billing_date).slice(0,10):hojeISO(); status.value=c.status||"ativo"; window.scrollTo({top:0,behavior:"smooth"})}
 async function ensureCustomer(av){if(av.customer_id) return av.customer_id; const ex=state.customers.find(c=>normalizar(c.name)===normalizar(av.client_name)&&String(c.phone||"").trim()===String(av.client_phone||"").trim()); if(ex) return ex.id; const novo=await safeInsert(sb.db,"customers",{company_id:sb.companyId,name:av.client_name||"Sem nome",phone:av.client_phone||null}); return novo?novo.id:null}
 async function salvar(ev){ev.preventDefault(); setErro(""); setInfo(""); if(!customerId.value) return setErro("Selecione o cliente."); if(!slaPlanId.value) return setErro("Selecione o SLA."); if(!startDate.value) return setErro("Informe a data de início."); if(!nextBillingDate.value) return setErro("Informe a próxima cobrança."); const payload={company_id:sb.companyId,customer_id:customerId.value,sla_plan_id:slaPlanId.value,start_date:startDate.value,next_billing_date:nextBillingDate.value,status:status.value||"ativo",name:name.value||null,amount:Number(amount.value||0)}; try{if(contractId.value){await safeUpdate(sb.db,"contracts",payload,[["id",contractId.value],["company_id",sb.companyId]]); setInfo("Contrato atualizado com sucesso.")} else {await safeInsert(sb.db,"contracts",payload); setInfo("Contrato criado com sucesso.")} await renderizarRecorrencia(opts)}catch(e){setErro("Falha ao salvar contrato: "+(e.message||e))}}
 async function processar(){setErro(""); setInfo(""); try{const r=await sb.db.rpc("fn_generate_contract_receivables",{p_company_id:sb.companyId}); if(r.error) throw r.error; const data=r.data||{}; const qtd=(typeof data==="object"&&data)?(data.created||data.count||data.qtd||0):0; setInfo(`Recorrências processadas com sucesso. Cobranças geradas: ${qtd}.`); await renderizarRecorrencia(opts)}catch(e){setErro("Falha ao processar recorrências. Rode a SQL do pacote antes de usar esse botão. Detalhe: "+(e.message||e))}}
 async function cancelar(id){try{await safeUpdate(sb.db,"contracts",{status:"cancelado"},[["id",id],["company_id",sb.companyId]]); setInfo("Contrato cancelado."); await renderizarRecorrencia(opts)}catch(e){setErro("Falha ao cancelar contrato: "+(e.message||e))}}
 async function renovar(id){try{const c=state.contratos.find(x=>x.id===id); if(!c)return; await safeUpdate(sb.db,"contracts",{status:"ativo",next_billing_date:c.next_billing_date||hojeISO()},[["id",id],["company_id",sb.companyId]]); setInfo("Contrato renovado/reativado."); await renderizarRecorrencia(opts)}catch(e){setErro("Falha ao renovar contrato: "+(e.message||e))}}
 form.addEventListener("submit",salvar); btnNovo.addEventListener("click",resetForm); btnProc.addEventListener("click",processar); slaPlanId.addEventListener("change",function(){const p=state.slaPlans.find(x=>String(x.id)===String(slaPlanId.value)); if(p&&!Number(amount.value||0)) amount.value=guessAmount(p)||""});
 alvo.addEventListener("click",async function(ev){const btn=ev.target.closest("button[data-action]"); if(!btn) return; const action=btn.getAttribute("data-action"), id=btn.getAttribute("data-id"), idx=btn.getAttribute("data-idx"), cid=btn.getAttribute("data-customer-id");
 if(action==="editar-contrato"){const c=state.contratos.find(x=>String(x.id)===String(id)); if(c) preencher(c); return}
 if(action==="cancelar-contrato"){await cancelar(id); return}
 if(action==="renovar-contrato"){await renovar(id); return}
 if(action==="usar-cadastro"){customerId.value=cid||""; window.scrollTo({top:0,behavior:"smooth"}); return}
 if(action==="converter-avulso"){const av=state.avulsos[Number(idx)]; if(!av) return; try{const real=await ensureCustomer(av); customerId.value=real||""; name.value=`Contrato recorrente - ${av.client_name||"Cliente"}`; window.scrollTo({top:0,behavior:"smooth"}); setInfo("Cliente avulso preparado para conversão. Agora selecione o SLA, valor e salve o contrato.")}catch(e){setErro("Falha ao preparar conversão do cliente avulso: "+(e.message||e))}}
 });
}catch(e){setErro("Falha ao carregar recorrência: "+(e.message||e)); if(alvo) alvo.innerHTML=panel("Recorrência","Não foi possível montar o módulo de recorrência.",`<div class="placeholder-big">Verifique o acesso às tabelas tickets, customers, contracts, sla_plans e receivables.</div>`)}
}
window.ModuloRecorrencia={renderizarRecorrencia:renderizarRecorrencia};})();